version: '3'

services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./_posts:/app/_posts
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --incremental --watch
